# Process to access ECHILD {#sec-access-process}

Substantive employees and PhD students at a UK university/institution who are Accredited Researchers can apply to access ECHILD. PhD students must be supervised by a fully accredited substantive employee who takes responsibility for the project. The following is the process to apply to access ECHILD data:

1. Obtain Full
   [Accredited Researcher status](https://www.ons.gov.uk/aboutus/whatwedo/statistics/requestingstatistics/approvedresearcherscheme).
1. Familiarise yourself with the [ECHILD User Guide](https://docs.echild.ac.uk/)
   and [Data Catalogue](https://www.echild.ac.uk/s/ECHILD_DataCatalogue_v31_20251209.xlsx). 
1. Ensure that your institution has 
   [Assured Organisational Connectivity](https://www.ons.gov.uk/aboutus/whatwedo/statistics/requestingstatistics/secureresearchservice/accessthedatasecurely)
   certified by the ONS Secure Research Service, or alternatively, check you can access the
   [SafePod Network](https://safepodnetwork.ac.uk/).
1. Contact the ECHILD team at UCL to discuss feasibility: 
   [ich.echild@ucl.ac.uk](mailto:ich.echild@ucl.ac.uk)
1. We recommend completing the 
   [UKSA Ethics self-assessment](https://uksa.statisticsauthority.gov.uk/the-authority-board/committees/national-statisticians-advisory-committees-and-panels/national-statisticians-data-ethics-advisory-committee/ethics-self-assessment-tool/),
   but it is not compulsory. 
1. Complete a project 
   [Application Form](https://www.echild.ac.uk/s/New_PASS_SRS_Application_Form_V20_ECHILD.docx)
   and a
   [Data Request Form](https://www.echild.ac.uk/s/ECHILD-Data-Request-Form-V21.xlsx),
   and submit to the ECHILD team.\
   *Note: We aim to provide feedback within 2 weeks of receiving a completed application form.*
1. Once your application has been approved by UCL, you will submit your application to the 
   [ONS PASS system](https://ons.metadata.works/browser/landing) for project accreditation.\
   *Note: applications take an average of 10 weeks to be processed by ONS.*
1. Finally, your organisation will need to sign a **non-negotiable**
   [Data Access Agreement](https://www.echild.ac.uk/s/ECHILD-Sublicence-Template_v30_COPY_TO_SHARE.pdf)
   (sublicense) with UCL.
