# How to access ECHILD {#sec-access-how}

## Five Safes

ECHILD is available to researchers through the ONS SRS [42], which follows the Five Safes Framework:
1.Safe People 2.Safe Projects 3.Safe Settings 4.Safe Outputs 5.Safe Data

Accredited Researchers Ethical & benefits public Secure technology Non-identifiable outputs Use de-identified data

## ECHILD cannot be linked to other data sources without further approval 

Researchers wishing to link additional datasets to ECHILD will need permission from the data controllers i.e., NHSE 
and DfE. In addition, the ECHILD team will consider the feasibility of such requests on a case-by-case basis and
encourage researchers to contact the team for further discussion. 

## Ethics Self-Assessment 

It is important to consider the ethical aspects of any study involving secondary analysis of de-identified 
administrative data; although the data are de-identified, no study is free of risk. Researchers applying to use ECHILD 
will be asked to complete a Self-Assessment form [43] to assess compliance of their proposed project with the 
ethical principles developed by the National Statistician’s Data Ethics Advisory Committee. 

## Access Conditions 

Researchers will have to demonstrate how their research will benefit the health and well-being of children and 
young people accessing health, education and social care services. More specifically, projects will have to fall under 
at least one of the agreed five research purposes described in Section 2.2. We do not have approval for non-UCL PhD 
students without a substantial contract at an applying institution to access ECHILD.
Researchers will be expected to:
1. State their use of ECHILD in any publication/presentation and acknowledge the ECHILD team in publications 
and reports, including the following acknowledgements/notes where possible: “We would like to 
acknowledge the contribution of the wider ECHILD Database support and programme management.”
2. Undertake appropriate Public and Patient Involvement and Engagement (PPIE) activities.
3. Refer to ONS guidance regarding pre-publication, publication and code file clearance. 
4. Notify and provide details in writing of all publications to UCL 14 days in advance of publication.
5. Notify and provide draft publications to the Department for Education 14 days in advance of any publication.
6. Include the following data sharing and funding statements in publications as defined by NHS England, the 
Department for Education, the ONS and ECHILD Database funders:
a) “The ECHILD Database uses data from the Department for Education (DfE). The DfE does not accept 
responsibility for any inferences or conclusions derived by the authors.”
b) “This work uses data provided by patients and collected by the National Health Service as part of 
their care and support. Source data can also be accessed by researchers by applying to NHS 
England.”
c) “We are grateful to the Office for National Statistics (ONS) for providing the Trusted Research 
Environment for the ECHILD Database. ONS agrees that the figures and descriptions of results in the 
attached document may be published. This does not imply ONS' acceptance of the validity of the 
methods used to obtain these figures, or of any analysis of the results.”
d) “The views in this publication do not necessarily reflect the views of UCL.”
7. Report how data quality issues were addressed. 
8. Share their code/script for data processing and analysis.
9. Prepare and send an annual report to the ECHILD team on the benefits of the research undertaken. 
19

## Process to access ECHILD 

Step Task
1. Contact ECHILD Team: ich.echild@ucl.ac.uk
2. Complete ethics self-assessment
3. Submit an application form to UCL
4. Obtain approval from UCL on feasibility and purpose
5. Submit the UCL-approved application form to ONS Research Accreditation Panel (RAP)
6. Obtain approval from RAP for release under Digital Economy Act (DEA) 
7. Sign Data Access Agreements with UCL & ONS Accredited Researcher Assurance Registration (ARAR) form.
8. UCL instructs ONS to provide access to a specified extract of ECHILD to named user(s)

## Accredited Research Status 

To access ECHILD researchers must become fully Accredited Researchers under the Digital Economy Act 2017 (DEA) 
as this enables researchers to carry out analysis and produce outputs on projects within a Trusted Research 
Environment such as the ONS Secure Research Service (SRS). To be a fully accredited researcher, individuals must 
have an undergraduate degree (or higher), including a significant proportion of maths or statistics. Otherwise, they 
must be able to demonstrate at least three years of quantitative research experience.[42]

## Assured Organisational Connectivity (AOC) 

An AOC is an agreement between your organisation and the ONS concerning how your organisation meets the 
required physical and system security standard to directly allow access to the SRS from your organisation or your 
home office space. All AOC agreements must be approved by the ONS and it is the responsibility of the researcher to
check if an institutional AOC is in place before applying for access to ECHILD.[44]
