# Hospital Episode Statistics {sec-hes}

HES contains hospital records for all NHS patients in England, including patient demographics and standardised 
codes for diagnoses, symptoms and procedures relating to the care they have received [@nhse2023c]. The datasets are collected 
by NHSE from hospital care providers and curated on an ongoing basis. However, data from other health providers 
such as General Practitioners (GPs) or pharmacies are not included. HES datasets are collated by financial year and 
following processing and quality assessment, the finalised datasets are released for secondary use and remain 
unchanged thereafter [@boyd2017a].

## Admitted Patient Care 

Records within the Admitted Patient Care (APC) dataset are called ‘hospital episodes’, and each episode relates to a 
period of care for a patient under a single consultant (consultant episode) within one hospital provider. The time 
from initial admission to discharge is called a ‘spell’, defined as ‘periods of continuous care in one provider 
institution’ and each admission spell can be made up of many episodes. APC data contain ‘Finished Admission 
Episodes’ (FAEs) which is the first episode in a spell of care, and ‘Finished Consultant Episodes’ (FCEs), which is a 
continuous period of care under one consultant [@boyd2017a; @nhse2023d]. Only FCEs occurring within the financial year (up to midnight 
                                                                                                       on 31st Mar) are included. Patients with an unfinished consultant episode in the current financial year will have their 
record represented as a finished episode in the next financial year of HES data [@unknown2021a].

Inpatient spell (single hospital)
A hospital admission commences 
when a patient is initially admitted 
for care and ends when a patient is 
discharged, transferred, or dies. 
One spell of admission encompasses
multiple episodes of care under a 
different consultant. 
Continuous Inpatient spell (across 
                            multiple hospitals)
In some instances, admitted patients 
that require specialised treatment 
may be transferred from one 
hospital to another more specialist 
hospital, e.g., transfer to a Children’s 
hospital. 
Figure 3.3 Hospital admission spells and episodes
12

## Attribute data: Hospital attendance 

Table 3.1 Overview of HES Attendance datasets 

Dataset Years Details
Outpatients (OP) [^1] 2003 to
2023
Outpatient appointments at English NHS hospitals and NHS commissioned activity in the independent sector (regardless of
                                                                                                          whether the appointment was attended or not) [@nhse2023e]. In 2003/04, the 
OP module was considered experimental and did not have complete 
coverage as not all providers completed data submissions [@nhse2023f].

Accident & Emergency
(A&E) [^2]
2007 to
2020
Attendance level dataset collecting information about the treatment 
received by patients attending A&E Departments, Minor Injury Units 
and Walk-In Centres, in England. 

Emergency Care 
Data Set (ECDS) [^3]
2020 to 
2023
In 2018, the A&E dataset was replaced by the ECDS which is now the 
national dataset for Urgent & Emergency care [@nhse2023g; @nhse2023h].

## Attribute data: Admission 

Table 3.2 Overview of HES Admission datasets

Dataset Years Details
Admitted Patient Care 
(APC) ^[See footnote 1.]
1997 to
2023
Episode-level dataset of patients admitted for treatment (i.e., requiring 
                                                          the use of a hospital bed), at NHS hospitals in England; includes 
delivery and birth data, up to 20 diagnostic codes per episode and 
procedure codes [@nhse2023d].

Critical Care (CC) ^[See footnote 1.] 2007 to 
2023
Episode-level dataset of patients admitted for treatment and receiving 
Critical Care (intensive care or high dependency care) at NHS hospitals 
in England. 

Treatment in adult designated wards where constant support and 
monitoring are required to maintain at least one organ (i.e., an 
                                                        Intensive Care or High Dependency Unit) [@nhse2023i].
         
         
[^1]: Diagnoses are recorded using the International Classification of Disease (ICD) version 10 and procedures are recorded using the 
Office of Population Censuses and Surveys (OPCS) version 4. Diagnoses and procedures have very low levels of completeness in 
the Outpatient dataset (5% and 26%, respectively) [@boyd2017a].

[^2]: Bespoke codes are used to record diagnoses and treatments [@nhse2023j]; however, these are much more limited than ICD-10 and 
OPCS-4 codes. Prior to 2012/13, the A&E module was considered experimental and did not have complete coverage as not all 
providers completed data submissions [@ons2023a].

[^3]: ECDS uses a subset of SNOMED CT codes to record diagnoses and treatments (amongst other variables) [@nhse2023k].
