# Attribute data: Mental Health 

Table 3.3 Overview of Mental Health datasets

Dataset Years Details
Mental Health Services 
Data Set (MHSDS)
2016 to
2023
Patient-level dataset that records all activity relating to patients who 
receive assessments and treatment from Mental Health Services in 
England, where the patient has (or is thought to have): either a mental 
health condition; a need for support with their mental well-being; a
learning disability; autism; or any other neurodevelopmental 
condition.[20]
Mental Health & 
Learning 
Disabilities Data Set
2014 to 
2016
The Mental Health & Learning Disabilities Data Set Data is collected 
from the health records of individual children, young people and adults 
who were in contact with mental health services.[21]
Mental Health 
Minimum Data Set 
(MHMDS)
2006 to
2016
The MHMDS was the preliminary dataset capturing data about the use 
of Mental Health Services in England. 
However, the MHMDS was superseded by the Mental Health & 
Learning Disabilities Data Set, which in turn was superseded by the 
MHSDS.

## Attribute data: Birth 

Table 3.4 Overview of Birth datasets

Dataset Years Details
Maternity Services 
Data Set (MSDS)
2015 to 
2023
The MSDS is a patient-level dataset that captures information about 
activity carried out by Maternity Services relating to a mother and
baby(ies), from the point of the first booking appointment until the 
mother and baby(ies) are discharged from maternity services. The 
MSDS collects records of each stage of the maternity service care 
pathway in NHS-funded maternity services and includes information 
not recorded in HES.[22, 23]
Birth Notification
Data
2001 to
2023
Birth notification is a document completed by the doctor or midwife 
present at birth occurring in an NHS facility in England, Wales and the 
Isle of Man. The baby's NHS Number is issued as part of the 'statutory 
notification of birth'. Birth notification data includes information that is 
not found in the birth registration data such as gestation age and 
ethnicity of the baby as stated by the mother.[24]
ONS Birth Registration 
Data1
1996 to 
2022
ONS Birth Registration Data includes information recorded when live 
births and stillbirths are registered as part of civil registration, a legal 
requirement, in England and Wales. The registration of births is a 
service carried out by the Local Registration Service in partnership with 
the General Register Office (GRO), in England and Wales. All registered 
births are included except very late registrations received more than 
14 months after the end of each reference year (there are fewer than 
100 of these for any given year).[25]

Inclusion of dataset within ECHILD is pending confirmation

## Attribute data: Other 

Table 3.5 Overview of Linked Mortality and Community Service datasets

Dataset Years Details
HES-ONS Linked 
Mortality Data
1998 to 
2023
Since January 1998, HES data have been routinely linked to mortality 
data as recorded by the Office of National Statistics,[26] and this 
information is also included in ECHILD.
Mortality data contains information taken from the death certificate 
for all deaths registered in England and Wales and includes cause of 
death, date and place of death. Information related to stillbirths is not 
available in this dataset.[26]

Community Services 
Data Set (CSDS)
2015 to
2023

The CSDS captures activity data about children and adults collected by 
Community Services, including health visiting teams. Such activities 
may take place in settings such as Health centres; Day care facilities; 
Schools or Community centres; Mobile facilities, or a patient's own 
home.[27]
Data are collected about children and adults e.g., personal, 
demographic or social circumstances; breastfeeding and nutrition; 
long-term conditions (disabilities), diagnoses and scored assessments. 
The CSDS is comprised of patient-level data from all publicly funded 
community services providers e.g., Foundation or Non-Foundation 
Trusts; Acute Trusts; Mental health Trusts, Community Healthcare 
Trusts, Independent sector providers and Local Authorities.
