# Education and social care data {#sec-data-npd}

The data collections detailed below are collated by the Department for Education (DfE).

The National Pupil Database (NPD) was formally established in 2002 based on including a 
pupil census record for every child in state education [@jay2019a; @education2023c]. The NPD is made up of modules of data that are collected by the DfE from schools, local authorities and exam-awarding organisations on an ongoing and statutory basis. Information collected as part of NPD is used for funding purposes, policy-making, generating statistics and research. The NPD modules included in ECHILD can be broadly grouped as pupil characteristics, educational outcomes and social care. 

NPD does not include information on pupils within private schools, or those being home-schooled, except in relation to public examinations (key stage 4 and 5). Approximately 7% of children [@jay2019a] are enrolled in a private 
school each year with up to 11% ever enrolled in a private school during their school 
career [@green2017a].

When a pupil first attends a state-funded school in England e.g., nursery or primary school, or has an education, health and care plan (EHCP) put in place, they are allocated a ‘Unique Pupil Number’ (UPN), which remains with the pupil throughout their school career regardless of any change in school or local authority [@education2019a]. Social care data is included in the NPD for children who have a UPN. Children receiving social care preschool entry who never have social care during their school years are therefore not included in ECHILD.

UPNs facilitate the transfer of school-based education and attainment data between schools, local authorities and central government and are stored within the NPD. Within ECHILD, a nationally unique and anonymised child-level identifier called the Anonymised Pupil Matching Reference (aPMR) can be used to link data across different years of data collection [@jay2019a].

**NPD data are provided for each academic year (1st August to 31st July). Regarding the labelling structure in the following sections, for example, the year 2001/2002 is labelled as 2002.**

## Pupil enrollment data collections

### School Census Pupil Level

Years available: 2001 to 2022 (Missing: 2020)

The School Census Pupil Level holds information on pupils enrolled in state-funded schools, including local authority-maintained schools, academies, city technical colleges and special schools. 

The census modules of the NPD are recorded at the enrolment level. Children who are registered in more than one educational setting will have multiple records in a census. The census modules of the NPD contain information such as age, gender, ethnicity, special educational needs (SEN) support, first language and free school meals (FSM) eligibility.

Data is collected termly: Autumn (October); Spring (January); Summer (May). 
From Spring 2013/14, the school census also includes pupils enrolled in Pupil Referral Units (previously collected in a separate census). 

The census  does not contain information for pupils enrolled in hospital schools or non-maintained independent schools (e.g., private schools) or who pursue an apprenticeship, traineeship, training, or work as part of their post-16 options [@education2024f; @education2022a].

After KS4, the School Census Pupil Level module only contains information for young people who continue in full-time post-16 education in schools or colleges.

### Early Years Census

Years available: 2008 to 2022

The Early Year Census holds data on children (all 2- to 4-year-olds) in state-funded early years care in any private, voluntary, and independent (PVI) sector nursery, with one or more children receiving funding from DfE. Data collected annually (January) [@education2024a].

The census modules of the NPD are recorded at enrolment level. Children who are registered in more than one educational setting will have multiple records in a census. The census modules of the NPD contain information such as age, gender, ethnicity, special educational needs (SEN) support, first language and free school meals (FSM) eligibility.

The Early Years Census only collects information for children who are taking up a government-funded place  [@education2024a]. All 3- and 4-year-olds in England are entitled to government funding; however, funding for 2-year olds is only for specific groups of children, such as those who are in care, who have an education, health and care plan, or whose parents are in receipt of certain benefits. Early years settings that do not have any children who receive direct government funding are not required to submit information via the Early Years Census.

### Pupil Referral Unit Census (PRU)

Years available: 2010 to 2013

Information on pupils enrolled in PRUs (a form of school for pupils unable to attend mainstream schools due to factors such as behavioural issues). From Spring 2013/14, these data are collected as part of the School Census.

As with all census modules of the NPD, these are recorded at enrolment level. Children who are registered in more than one educational setting will have multiple records in a census. The census modules of the NPD contain information such as age, gender, ethnicity, special educational needs (SEN) support, first language and free school meals (FSM) eligibility.

### Alternative Provision Census (AP)

Years available: 2008 to 2022

The Alternative Provision Census is an annual census (collected in January) of pupils who are educated in alternative provision placements [@education2024f]. Provision must be arranged by the local authority or school otherwise the child would not receive suitable education e.g., due to illness or if they received a fixed-term exclusion.

The census modules of the NPD are recorded at enrolment level. Children who are registered in more than one educational setting will have multiple records in a census. The census modules of the NPD contain information such as age, gender, ethnicity, special educational needs (SEN) support, first language and free school meals (FSM) eligibility.

## School level data collections

### School Level Census

Years available: 2005 to 2022

Collects information from primary schools, secondary schools, special schools, maintained nurseries and academies and pupil referral units three times a year. Private schools are not included.

### Get Information about Schools (GIAS)

Years available: 2020 to 2022

GIAS (formerly ‘Edubase’) is the DfE’s public register or dataset containing school characteristics. GIAS is updated whenever a school updates their details. GIAS also maintains information for several organisation types and is used by the DfE to contact establishments, update systems, perform analysis and inform policy decisions [@education2024d].

## Educational Outcomes data collecitons

### Early Years Foundation Stage Profile (EYFSP)
Years available: Academic years from 2003 to 2019, and 2022 (Missing: 2020)

The Early Years Foundation Stage Profile contains information on statutory assessment of children in the final year of the Foundation Stage (Reception year).

### Key Stage 1 (KS1) 
Years available:  Academic years from 1998 to 2019, and 2022 (Missing: 2020 to 2021)

Information on assessment of learners by the end of year 2 of schooling (age 7).

### Key Stage 2 (KS2) - Exam and Pupil

Years available: Exam – Academic years from 2007 to 2019, and 2022 (Missing: 2020 to 2021); Pupil – Academic years from 1996 to 2019, and 2022 (Missing: 2020 to 2021)

Information on assessment of learners by the end of year 6 of schooling (age 11). 2009/10 Industrial action - teacher boycott affected KS2 SATs (approx. date: May 2010). 

### Key Stage 3 (KS3) – Pupil and Teacher Assessment
Years available: KS3 – Academic years from 1999 to 2006; Pupil – Academic years from 2007 to 2008; Teacher Assessment – Academic years from 2009 to 2013

Information on assessment of learners by the end of year 9 of schooling (age 14).

### Key Stage 4 (KS4) – Exam and Pupil

Years available: Exam – Academic years from 2002 to 2021; Pupil – Academic years from 2002 to 2021

Information on the assessment of learners by the end of year 11 of schooling (age 16). Attainment data are collected for all pupils when they complete nationally recognised assessments at KS4, including those in private schools and further education state sector colleges [@education2015a].

###	Key Stage 5 (KS5) – Exam and Student

Years available: Exam – Academic years from 2003 to 2021; Student - Academic years from 2003 to 2021

Information on post-16 assessment of learners in school, sixth forms and Further Education colleges. Attainment data are collected for all pupils when they complete nationally recognised assessments at KS5. Attainment data are collected for all pupils when they complete nationally recognised assessments at KS4 and KS5, including those in private schools and further education state sector colleges [@education2015a].

### Absences

Years available: For Term 2, Academic year 2022 (only); For Term 3, Academic years from 2006 to 2019, and 2022 (Missing: 2020 to 2021)

Information on authorised and unauthorised absences, including reasons for absence, derived from the termly School Census, for 4- to 15-year-olds. Absence data are not recorded for boarding pupils [@education2023d]. Schools provide information about the reasons for absences (e.g., due to illness, medical appointments, etc) though approximately 1% of schools are able only to provide overall authorised and unauthorised absences [@education2023d]. Absence data were first collected for 4-year-olds in the 2012/13 academic year. In 2012/13, the period of collection of absence data was also extended to the end of the summer term. In previous years, absence data were only collected for the first half of the summer term. Absence data include ‘persistently absent’ indicators (the threshold for which varies by academic year, though users can specify their own thresholds).

### Exclusions

Years available: Academic years from 2002 to 2022

Information on pupil fixed term and permanent exclusions as collected in the termly School Census. Compared to other modules of the NPD, there is a lag in data availability related to exclusions. Data are made available in the summer for the preceding academic year; for example, data for the academic year 2017/18 is released in summer 2019 [@education2017a].

### National Client Caseload Information (NCCIS)

Years available: Academic years from 2013 to 2022

Information on employment destinations. Unlike the School Census Pupil Level module (which only contains information for young people who continue in full-time education post-16), NCCIS includes information about the post-16 activities of all young people aged 16 to 19 years (or aged 16 to 24 years for young people with a current Education, Health and Care (EHC) plan) [@education2023a]. This activity information is collected by local authorities and used by the DfE to estimate Not in Education, Employment or Training (NEET) rates for young people in England.


## Social Care data collections

The CLA and CIN modules of the NPD contain two different identifiers. The first is an 
encrypted version of the identifier assigned by the local authority (child ID) that 
allows social care records for the same individual to be linked over time. However, 
this identifier is local authority specific and so it is not possible - using this 
identifier - to link records for the same individual across different local 
authorities [@emmott2019a; @mcgrathlone2016b].

The second is the aPMR, based on Unique Pupil Numbers (UPNs) where available. UPNs 
have been returned to DfE by local authorities in the CLA module from 1 April 2005 
and in the CIN module from 1 October 2008 (i.e., from when the CIN census began). 
Where a UPN is returned, the aPMR is available, enabling linkage to the NPD education 
records. For data before April 2005, it is not possible to link education and the CLA 
datasets.

It is not possible to link social care and education records for 
children who were only in contact with children’s social care services before their 
UPN was assigned (i.e., for most children who were a child in need or looked after 
before school age). Previous research has shown that 20% of children who are ever 
looked after during childhood are only looked after before age 5 [@mcgrathlone2022a].

###Children Looked After Return (CLA) 

Years available: 2006 to 2022

Information on children looked after by a local authority in England for a period of at least 24 hours [@mcgrathlone2016b; @education2024c; @education2024i]. The data include information on date and type of placement, use of respite care, and exiting from care, including through adoption. Does not include information on informal fostering arrangements.

### Children in Need Census (CIN) 
Years available: 2008 to 2022 

Has information covering all children who are referred to children’s social care services, including information on whether they were assessed and found to be in need [@emmott2019a; @education2024h; @education2023e]. The CIN census also contains information on children who are subject to a Child Protection Plan (CPP).

### Children in Need Census Assessment Factors
Years available: 2009-2022

[Pending]

### Children in Need Census Assessments

Years available: 2015 to 2022

[Pending]

###	Children in Need Census Disabilities

Years available: 2009 to 2022

[Pending]


## Individualised Learner Record data collection

Years available: 2001 to 2022

Training providers within the Further Education (FE) and skills sector in England 
use the ‘Individualised Learner Record’ (ILR) to collect information about each of the 
learners in their sector, the learning undertaken, and the learning outcome, e.g., 
sectors include Adult skills, Community Learning, Skills Bootcamps, 16-19 (excluding 
Apprenticeships) [@education2023b].

ILR data are used to ensure public money distributed through the Education & Skills 
Funding Agency is being spent in line with government targets, for quality, value for 
money, planning and supporting future initiatives.

An ILR ‘Year’ of data, typically runs from 1st August to 31st July and in May 2023.
