# Key research purposes {#sec-echild-key-purposes .unnumbered}

ECHILD will only be used for research that has a clear public benefit in England and Wales to improve the health and well-being of children and young people accessing health, education and social care services. The specific research purposes (permitted uses) are below (in bold) with examples of relevant research questions.

1. **Informing preventative strategies by Healthcare and Education services** e.g., do disabled children attending schools, or living in areas that provide a good level of disability support in school or through social care services, have lower rates of unplanned hospital contacts compared with less supportive schools/areas? 
2. **Informing children and their parents** e.g., about variation in special educational needs support and outcomes for children with chronic health conditions or disability.
3. **Informing education and clinical practice** e.g., investigating whether associations between chronic health conditions and lower school attainment are explained by school absence. 
4. **Identifying groups who could benefit from intervention** e.g., what are the health outcomes of children post age 16 who have contact with social care services or have special educational needs? 
5. **Understanding the most effective methods for working with linked health and education data** e.g., what are the most effective methods for working with linked health and education data?
  