name: Render and deploy website to preview

on:
  push:
    branches: main
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: "preview"
  cancel-in-progress: true

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get timestamp
        shell: bash
        run: |
          echo "RUN_TIMESTAMP=$(date +'%Y%m%d_%H%M%S%Z')" >> "$GITHUB_ENV"
          
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Add subtitle
        shell: bash
        run: |
          printf "\n  subtitle: \"$RUN_TIMESTAMP\"\n" >> web_source/_quarto.yml
      #   
      # - name: Install dependencies for asdf R plugin
      #   run: apt-get install build-essential libcurl3-dev libreadline-dev gfortran liblzma-dev liblzma5 libbz2-1.0 libbz2-dev xorg-dev libbz2-dev liblzma-dev libpcre2-dev
      #   
      # - name: Instal asdf and tools
      #   uses: asdf-vm/actions/install@v2
      
      - name: Install Inkscape
        shell: bash
        run: |
          sudo apt update
          sudo apt install inkscape

      - name: Install and set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tinytex: true

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.5.1
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
          
      - name: Load cached Python venv
        id: cached-poetry-dependencies
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install Python dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction --no-root

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.1'

      - name: Install R Dependencies
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1
          
      - name: Render pdf
        shell: bash
        run: |
          quarto render web_source/ --to pdf --output-dir pdf/quarto-buggyness --output "ECHILD-User-Guide_$RUN_TIMESTAMP.pdf"

      - name: Render website
        uses: quarto-dev/quarto-actions/render@v2
        with:
          path: web_source/
          to: html

#      Cloudflare deploy
      - name: Deploy to cloudflare
        id: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          accountId: ${{ secrets.CLOUDFLARE_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_PAGES_TOKEN }}
          command: pages deploy ./_docs --project-name=echild-docs --branch=preview --commit-dirty=true
          
      - name: LINK TO WEBSITE PREVIEW
        env:
          DEPLOYMENT_URL: ${{ steps.deploy.outputs.deployment-url }}
        run: echo $DEPLOYMENT_URL
        
